### ISSUE TITLE
Add Linux aarch64 and ppc64le builds

### ISSUE THREAD

**Issue by matthewfeickert** [conda-forge/cuda_histogram-feedstock#1]
@Saransh-cpp Can you try to add aarch64 and ppc64le builds by adding the following to `conda-forge.yml` in a PR from your personal fork of this feedstock

```yaml
build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
provider:
  linux_aarch64: default
  linux_ppc64le: default
test: native_and_emulated
```

(c.f. https://conda-forge.org/docs/maintainer/conda_forge_yml/#build-platform) and then in the PR rerender with `@conda-forge-admin, please rerender` (and bump the build number)?
